[book]
title = "NexSign Documentation"
author = "Kenonekeys"
description = "Documentation for the NexSign IPA Signing System"
language = "en"

[build]
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "dark"
additional-css = ["theme/css/nexsign.css", "theme/css/nexsign-dark.css"]
additional-js  = ["theme/js/nexsign.js"]
