name: NexSign
options:
  bundleIdPrefix: com.example
configurations:
  Debug: debug
  Release: release
settings:
  INFO_PLIST_FILE: Info.plist

targets:
  NexSign:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/NexSign
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.NexSign
